### ISSUE TITLE
Allow adding import statement after existing imports

### ISSUE THREAD

**Issue by bluwy** [unjs/magicast#122]
### Describe the feature

Currently imports added (with `$add`) prepends before any other import statements in the file. There's also a TODO to consider appending instead:

https://github.com/unjs/magicast/blob/7b3f0bd9bdbc07d7c66408645a5dcd309511119e/src/proxy/imports.ts#L155-L165

It would be nice if we can add import statements after existing imports.

---

There's a comment at https://github.com/unjs/magicast/issues/45#issuecomment-1506670632 that suggests adding `$append` and `$prepend` to all the nodes. Maybe we can apply the same idea for `.imports` only for now?

---

I'm trying to migrate Astro to use this, but I think this issue is the only blocker before it's ready: https://github.com/withastro/astro/pull/11772. There's other new lines formatting difference, but I think it's not a big deal.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Yeah sure! `$append` and `$prepend` sounds good to me.
