### ISSUE TITLE
Add builders.raw to use raw code

### ISSUE THREAD

**Issue by hugoattal** [unjs/magicast#35]
First of all, that's awesome what you guys are building 🥳!

---

### Describe the feature

I suggest being able to use builders with raw code.

Here's an example:
```ts
const ast = builders.functionCall("foo", "bar", 12, builders.raw("baz"));
const result = generateCode(result);
console.log(result.code) // 'foo("bar", 12, baz)'
```

Here, it's just to add variables in `functionCall`.

But the broader use case would be to be able to create any code, even if some builders function of magicast are missing.

For example, I would be able to do this
```ts
const ast = builders.raw("const foo = {bar:'baz'}");
const result = generateCode(result);
console.log(result.code) // 'const foo={bar:"bar"};'
```

While waiting to have builders to do it the "proper" way:
```ts
const ast = builders.assignment(
    "foo",
    builders.object([
        {
            key: "bar",
            value: builders.literal("baz")
        }
    ]),
    {
        const: true
    }
);
const result = generateCode(result);
console.log(result.code) // 'const foo={bar:"baz"};'
```

Wdyt?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Will be in the next release https://github.com/unjs/magicast/commit/4983f47c01fb9c5316d0d4491ad578cd679649ca
