### ISSUE TITLE
Support satisfies keyword

### ISSUE THREAD

**Issue by thdxr** [unjs/magicast#36]
### Describe the feature

Looks like it throws an error when it encounters the satisfies keyword currently

can probably just ignore it for now would unblock me

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Upstream issue: https://github.com/benjamn/recast/issues/1281

**Comment by benjamn** [comment]
Try `npm i recast@next`? https://github.com/benjamn/recast/issues/1281#issuecomment-1535506691

**Comment by Andarist** [comment]
I'm not sure what's exactly the difference but it seems that perhaps this issue here wasn't exactly blocked by `recast`. I opened a PR with a fix and some basic tests without updating `recast`: https://github.com/unjs/magicast/pull/55
