### ISSUE TITLE
Missing castings

### ISSUE THREAD

**Issue by hugoattal** [unjs/magicast#37]
### Describe the feature

Hey 🙂!

So I'd like to parse any code using `builder.raw`, but it fails on some castings.
For example, I'd like to generate `foo(bar)` (`bar` being a variable), doing it like this does not work:

```ts
builders.functionCall("foo", builders.raw("bar"));
```

Here are a few more examples.

```ts
const result = builders.raw("bar()");
console.log(generateCode(result)); // works
```

```ts
const result = builders.raw("bar"); // MagicastError: Casting "Identifier" is not supported
console.log(generateCode(result));
```

```ts
const result = builders.raw("() => 'a'"); // MagicastError: Casting "ArrowFunctionExpression" is not supported
console.log(generateCode(result));
```

I can help with the implementation if needed!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Nice spotting! Indeed we have a lot to improve. PR welcome!

**Comment by denis-sokolov** [comment]
Another one to the list is FunctionDeclaration (#43).
