### ISSUE TITLE
Keys are not enumerable on `exports` and `imports` 

### ISSUE THREAD

**Issue by tcK1** [unjs/magicast#38]
### Environment

magicast: `0.2.1`
Node: `v16.17.0`

### Reproduction

[Here's](https://codesandbox.io/p/sandbox/elastic-bas-locc5z?file=README.md) a Codesandbox with an example.

This is the test snippet:

```js
import { parseModule } from "magicast";

const mod = parseModule(`
import test from './foo'
export default defineConfig({ foo: 'bar' })
`);

console.log(mod.imports);
console.log(Object.keys(mod.imports));
console.log(mod.exports);
console.log(Object.keys(mod.exports));
```

### Describe the bug

Both `imports` and `exports` are empty, even when the source string contains both.

**Comment by xiaochengzi6** [comment]
Yes, I also found this problem when I tried to use the 'import' or 'export' attribute value because this is actually an empty object.
~~~js
const value = parseModule(
  `export default function a () {}`
)

// value
{
  '$ast': Node {
    type: 'Program',
    start: 0,
    end: 31,
    loc: SourceLocation {
      start: [Object],
      end: [Object],
      filename: undefined,
      identifierName: undefined,
      lines: [Lines],
      tokens: [Array],
      indent: 0
    },
    sourceType: 'module',
    interpreter: null,
    body: [ [Node] ],
    directives: []
  },
  '$code': 'export default function a () {}',
  '$type': 'module',
  exports: {},
  imports: {},
  generate: [Function (anonymous)]
}
~~~

**Comment by xiaochengzi6** [comment]
Looking at the project source code, I found that the 'exports' or' imports' field uses Proxy's 'get' to intercept attribute lookup by traversing the ast tree and using'set' to intercept attribute changes to modify the ast node directly. Sounds cool, but it also creates problems.
~~~js
const { parseModule } = require("magicast");

const mod = parseModule(`export default defineConfig({ foo: 'bar' })`);

//  I can't get the contents of the object directly
console.log(mod.exports.default)               // {}
console.log(mod.exports.default.$args)         // {} 
console.log(mod.exports.default.$args[0].foo)  // bar


mod.exports.default.$args.push('b')

console.log(mod.exports.default.$args)        // {}

const result = mod.generate()
console.log(result)
/**
 * {
 *   code: "export default defineConfig({ foo: 'bar' }, 'b');",
 *   map: undefined
 * }
 */
~~~
This is very inconvenient in use. If I solve this problem, I may abandon the way of 'Proxy'. Is that what we want?

**Comment by antfu** [comment]
It's a known bug, I will find a way to fix it. I think moving away from Proxy is not an ideal solution as we want it to be dynamic reflecting to the ast.

**Comment by tcK1** [comment]
Thanks for the fix, @antfu! 😊
