### ISSUE TITLE
Named default export will cause error

### ISSUE THREAD

**Issue by luruozhou** [unjs/magicast#49]
### Environment

magicast: 0.2.3

nodejs:  v14.18.0

### Reproduction

 ``` config.js ```
```
const data = {
};

export default data;
```
```index.js ```
```
import {loadFile} from "magicast";

async function run() {
    const mod = await loadFile("./config.js");
    mod.exports.default.name = 'jim';
}

run();
```

### Describe the bug

run ```index.js``` will show the error below:

```UnhandledPromiseRejectionWarning: TypeError: 'set' on proxy: trap returned falsish for property 'name'```

### Cause analysis
<img width="526" alt="image" src="https://user-images.githubusercontent.com/10755486/233032853-08be57dc-eae0-4f4c-b41c-997264c81a94.png">
As shown above,  the code does not distinguish whether a declaration is an Identifier or other situations.

**Comment by antfu** [comment]
Currently, Magicast will not be able to solve that, but we are considering having some feature to forward variable references. I also added some notes to make this clear: https://github.com/unjs/magicast#notes

Thanks
