### ISSUE TITLE
[feature request] isolating/extracting modules

### ISSUE THREAD

**Issue by Hebilicious** [unjs/magicast#67]
### Describe the feature

Thanks for making magicast, I use it a lot ! There's something I would like to do :

Given this source file 

```ts
export const A = "a"
export const B = "b"
export const C = "c"
```
I want to create 3 other files that look like this (ie I want to drop the other exports)

```ts
export const A = "a"
```

```ts
export const B = "b"
```

```ts
export const C = "c"
```

As far as I know the only way to do this would be to call loadFile 3 times, and to call `delete file.exports[letterToDrop]` 2 times for each output file.

Would it be possible to have an API that allows this :

```ts
const mod = await loadFile();
const a = isolate(mod.exports["A"])
const b = isolate(mod.exports["B"])
const c = isolate(mod.exports["C"])
generateCode(a) //export const A = "a"
generateCode(b) //export const B = "b"
generateCode(c) //export const C = "c"
``` 

We could also allow an array of exports : 

```ts
const ab = isolate([mod.exports["A"], mod.exports["B"]])
generateCode(ab) //export const A = "a";export const B = "b";
```

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
It's already possible with:

```ts
  const code = `export const A = "a"
  export const B = "b"
  export const C = "c"
  `

  const mod = parseModule(code)

  const a = parseModule('')
  a.exports.A = mod.exports.A

  expect(generateCode(a).code)
    .toMatchInlineSnapshot('"export const A = \\"a\\";"')
```

I don't feel it's necessary to introduce a new helper, isn't it?

**Comment by Hebilicious** [comment]
@antfu I didn't think of doing this, thank you !

My issue is that for a more advanced scenario it won't work (I tried copying the ast): 

```ts
    const code = /* ts */`
    import { b } from "./something"  
    const something = "a"
    export const A = something + b
    export const B = b
    `
  const a = parseModule('')
  a.$ast = mod.$ast
  delete a.exports.B
  ```
  
Which doesn't work... AFAIK the only solution is to reload the file multiple times, and to use `delete` as many times I needed.
I guess I could also achieve that by removing the export keyword (`export const B` => `const B`) and applying tree shaking with esbuild.
It would be nice if Magicast could support this use case (ie removing export keywords or isolating an export).

But maybe this is out scope for magicast ?

**Comment by antfu** [comment]
I see. However, magicast currently does not support scope tracking (it turns out to be a very complex task, which might go beyond magicast's scope). For your specific case, I think using `delete` is a fine solution, that you can wrap as a function. For tree-shaking, you can pass the code to esbuild after the export removal and it should do the job.

Closing this as I see it is probably out-of-scope, while there are workaround/solutions available.
